arena:
  world: ""
  spawn: { x: 0.5, y: 64.0, z: 0.5, yaw: 0.0, pitch: 0.0 }
  bounds:
    pos1: { x: -10.0, y: 0.0, z: -10.0 }
    pos2: { x: 10.0, y: 255.0, z: 10.0 }
settings:
  debug: false
  keepInventoryInArena: true
  fallDamageInArena: false
  crystalDamageMultiplier: 0.8
  simulate:
    windcharge_when_blocked: true
    windburst_when_blocked: true
  bot:
    baseHealth: 40.0
    infiniteTotems: true
    knockbackResistance: 0.3
    hitRange: 2.8
    attackCooldownTicks: 12
  difficulty:
    EASY:   { speed: 0.20, strafe: 0.8, reachBonus: 0.0 }
    NORMAL: { speed: 0.26, strafe: 1.0, reachBonus: 0.1 }
    HARD:   { speed: 0.32, strafe: 1.2, reachBonus: 0.2 }
    INSANE: { speed: 0.38, strafe: 1.5, reachBonus: 0.3 }
