name: BotTrainer
version: "${version}"
main: com.nowheberg.bottrainer.BotTrainerPlugin
api-version: "1.21"
author: Now-Heberg
website: https://now-heberg.com
softdepend: [StrikePractice]
commands:
  bot:
    description: Lance un entraînement avec un bot.
    usage: /bot <joueur> <difficulte> <mode> <temps>
    permission: trainbot.use
  botarena:
    description: Configure l'arène.
    usage: /botarena <setspawn|setbounds|info>
    permission: trainbot.admin
  botstop:
    description: Stoppe ta session d'entraînement (ou celle d'un autre pour les admins).
    usage: /botstop [joueur]
    permission: trainbot.use
permissions:
  trainbot.use:
    description: Lancer un entraînement et stopper sa propre session.
    default: false
  trainbot.admin:
    description: Configurer l'arène et gérer toutes les sessions (dont celles des autres).
    default: false
