name: Build (Java 21)

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Set up Gradle (CLI 9.1.0)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 9.1.0

      - name: Generate Gradle Wrapper (9.1.0)
        run: gradle wrapper --gradle-version 9.1.0

      - name: Build with Wrapper
        run: ./gradlew build --stacktrace

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: BotTrainer-artifacts
          path: build/libs/*.jar
