name: Build (Java 21)

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      # Utilise Gradle 9.1.0 sans wrapper local
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 9.1.0

      - name: Build
        run: gradle build --stacktrace

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: BotTrainer-artifacts
          path: build/libs/*.jar
